### PR TITLE
Add some keywords to package.json

### PR DESCRIPTION
**Pull request by hakimio**
You've made an awesome library (thank you very much for that), but it can be a bit tricky to google it. So, I've added some keywords to help others find it.
Another good way to promote it would be by writing a short article on medium explaining how to easily add smooth scrolling to Angular project.

PS: feel free to modify this PR.

### CODE REVIEW

**Comment by Seemspyo** [comment]
@hakimio Thanks!

I already wrote down keywords in [package root](https://github.com/Seemspyo/ngx-smooth-scroll/blob/master/projects/ngx-smooth-scroll/package.json), but I think your suggestion is reasonable.

**Comment by hakimio** [comment]
@Seemspyo Sorry, thought that one was the library `package.json`. 
Anyway, there is a minor issue with the library `package.json`. When installing it with Angular version higher than 7, I get peer dependency mismatch warning. Can you change the peer dependencies to the following:
```json
"peerDependencies": {
    "@angular/common": ">7.0.0",
    "@angular/core": ">7.0.0"
  }
```

**Comment by hakimio** [comment]
Also, since you are using `rxjs` in the library, it might be a good idea to add it to peer dependencies as well.

**Comment by Seemspyo** [comment]
@hakimio I will check about peerDependencies ASAP. But feel free to send a pull request yourself at anytime(I'm kind of busy this days 😂).

Fyi, since this is my first npm package, and the first time I wrote this module I didn't know deep about angular's design patterns(this package currently heavily rely on Web APIs which is not ideal for angular's purpose).

So I thinking about complete re-design in v2. But I'm a bit busy so I can't tell when it will be.

I'm open with any suggestion about v2. And since this is not a popular project, your feedback means a lot to me.

**Comment by hakimio** [comment]
@Seemspyo I can create a PR to fix package dependencies tomorrow, but it's just a minor warning when installing the library. So, it's nothing to worry about.

Talking about Angular's design patterns, while there might be some minor improvements you could make to the directive, the service seems to be perfectly good as it is and that's what I am using. If you are busy right now, v2 can wait.

**Pull request merged**
